LearningDjangoWebProject/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('', include('studyabroadMIS.urls')),
	path('store/', include('store.urls')),
    
    path('admin/', admin.site.urls),
]

store/urls.py
from django.urls import path

from . import views

app_name = 'store'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),   
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),  
]

studyabroadMIS/urls.py
from django.urls import path

from . import views

app_name = 'studyabroadMIS'
urlpatterns = [
    path('', views.index, name='index'), 
]

store/models.py
import datetime
from django.db import models
from django.utils import timezone
# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        return self.pub_date>=timezone.now - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text
    
    

studyabroadMIS/models.py
from django.db import models

# Create your models here.

store/views.py
from django.shortcuts import render,get_object_or_404
from django.http import Http404, HttpResponseRedirect,HttpResponse
from django.template import loader
from django.urls import reverse
from .models import Question,Choice
# Create your views here.
def index(request):
    # return render(request,'store/index.html')
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    template = loader.get_template('store/index.html')
    context = {
        'latest_question_list': latest_question_list,
    }
    return render(request, 'store/index.html', context)  
    # return HttpResponse(template.render(context,request))  # context和request位置不能交换！

def detail(request, question_id):
    #try:
    #    question = Question.objects.get(pk=question_id)
    #except Question.DoesNotExist:
    #    raise Http404("Question does not exist")
    #return render(request,'store/detail.html',{'question':question})
    #return HttpResponse("You're looking at the results of question:" +"<h1>"+str(question)+"</h1>")
    question = get_object_or_404(Question,pk=question_id)
    #return HttpResponse("You're looking at the results of question:" +"<h1>"+str(question)+"</h1>")
    return render(request,'store/detail.html',{'question': question})
    # 对应的html中的注释，forloop.counter 指示 for 标签已经循环多少次。 POST 表单（它具有修改数据的作用），所以我们需要小心跨站点请求伪造对内部 URL 的 POST 表单都应该使用 {% csrf_token %} 模板标签来预防

def results(request, question_id):
    # response = "You're looking at the results of question %s."
    question = get_object_or_404(Question,pk=question_id)
    #return HttpResponse(response % question_id)
    return render(request,'store/results.html',{'question':question})


def vote(requset,question_id): 
    question = get_object_or_404(Question,pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=requset.POST['choice'])  #request.POST 是一个类字典对象，让你可以通过关键字的名字获取提交的数据。 这个例子中， request.POST['choice'] 以字符串形式返回选择的 Choice 的 ID。 request.POST 的值永远是字符串。
    except(KeyError,Choice.DoesNotExist):                           # request.POS后面是中括号
        return render(requset,'store/detail.html',     
                      {
                          'question':question,
                          'error_message':"You didn't select a choice.",
                      })
    else:
        selected_choice.votes+=1
        selected_choice.save()
        return HttpResponseRedirect(reverse('store:results',args=(question_id,)))   # reverse 等价于'/stire/3(id)/results/'

studyabroadMIS/views.py
from django.shortcuts import render,get_object_or_404
from django.http import Http404, HttpResponseRedirect,HttpResponse
from django.template import loader
from django.urls import reverse
# Create your views here.
def index(request):
    # return render(request,'store/index.html')
    template = loader.get_template('index.html')
    context = {
        'context_test': "this is context_test",
    }
    # return render(request, 'index.html', context)  
    return HttpResponse(template.render(context,request))  # context和request位置不能交换！
    # return HttpResponse("请求路径:{}" .format(request.META))

store/templates/store/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'store:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
    <input type="submit" value="Vote">

</form>

 

store/templates/store/results.htm
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

studyabroadMIS/templates/index.html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Study abroad</title>
    <!--
            <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
            <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
    -->
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
    <script src="{% static 'jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap.min.js' %}"></script>

    <script>
        'use strict';//在strict模式下运行的JavaScript代码，强制通过var申明变量，未使用var申明变量就使用的，将导致运行错误。
        window.onload = function () {
            //alert('hello');
            //document.getElementById("parameter_list").style.display = "none";
            var a = 1;
            console.log(a);
            console.log(0 / 0);
            console.log('\u4e2d\u6587');
            console.log(`this
                    is
            multiline str`);
            var xiaohong = {
                name: 'xiaohong',
                age: 18,
                'midle-school': 'no.1 school'
            };
            console.log(xiaohong['midle-school'])
            console.log(xiaohong.toString)


            var a = ['A', 'B', 'C'];
var s = new Set(['A', 'B', 'C']);
var m = new Map([[1, 'x'], [2, 'y'], [3, 'z']]);
for (var x of a) { // 遍历Array
    console.log(x);
}
for (var x of s) { // 遍历Set
    console.log(x);
}
for (var x of m) { // 遍历Map
    console.log(x[0] + '=' + x[1]);
}
        }



    </script>
</head>
<body>
    <div class="container">
        <div class="row" id="test">
            <div class="col-mid-3">
                <h1>{{request.user}}</h1>
                <h1>{{context_test}}</h1>
                <ul class="alert" id="parameter_list">
                    {%for i in request.META%}
                    <li class="alert-link"><a href="#">{{i}}</a></li>
                    {% endfor %}
                </ul>
            </div>

        </div>
    </div>


</body>
</html>